### ISSUE TITLE
FR: Hover for full tag render

### ISSUE THREAD

**Issue by RabaDabaDoba** [darrenkuro/obsidian-basetag#12]
I got a snippet that when you hover on the tag you get the full version of it. It works for regular dark and light mode since it uses the default obsidian css variables. 

This would be a nice feature within the plugin. 

```css

a.tag.basename-tag::after {
  content: attr(href);
  position: absolute;
  top: unset;
  left: unset;
  transform: translateX(-50%) scale(0);
  transform-origin: top center;
  background: var(--background-modifier-active-hover);
  color: var(--text-normal);
  padding: 6px 10px;
  border-radius: var(--radius-s);
  white-space: nowrap;
  margin-top: 5px;
  transition: transform 0.2s ease;
  pointer-events: none;
  z-index: 10;

}

a.tag.basename-tag:hover::after {
  transform: translateX(-50%) scale(1);
}


```
